Repository WING-NUS/SSID, pull requests merged in 2022-07, with the labels that each got.

#141 submission count is 0 for some zip file from Mac
  app/controllers/assignments_controller.rb
  lib/submissions_handler.rb
Labels: bug

#146 Student records across modules
  app/assets/images/link.svg
  app/assets/stylesheets/submission_logs.css.scss
  app/controllers/application_controller.rb
  app/controllers/assignments_controller.rb
  app/controllers/submission_logs_controller.rb
  app/controllers/submission_similarities_controller.rb
  app/models/course.rb
  app/models/guest_users_detail.rb
  app/models/user.rb
  app/services/courses_service.rb
  app/views/assignments/index.html.erb
  app/views/submission_logs/index.html.erb
  config/routes.rb
Labels: enhancement

#189 Developer guide
  doc/DeveloperGuide.md
  doc/SettingUp.md
Labels: documentation
