Repository WING-NUS/SSID, pull requests merged in 2023-09, with the labels that each got.

#311 Correct mapping infotip
  app/views/assignments/_form.html.erb
Labels: Type: Bug

#312 Add winnowing infotip
  app/views/assignments/_form.html.erb
Labels: Type: Bug

#303 Enable skip confirmation when seeding
  db/seeds.rb
Labels: Type: Bug

#318 Update sever required gems, developer documentation
  Gemfile
  Gemfile.lock
  doc/developer_guide.md
Labels: Type: Refactor

#316 Add Landing Page Project Roadmap to docs
  README.md
  doc/SSID-Landing-Page-ProjectRoadmap.pdf
Labels: Type: Documentation

#334 Update Beginner Docs for WSL Support
  README-v-Beginner.md
Labels: Type: Documentation
