Repository WING-NUS/SSID, pull requests merged in 2023-12, with the labels that each got.

#382 Allow API keys of admin to access all courses
  lib/api_keys_handler.rb
Labels: bug

#372 Add PDF Generation API feature
  .github/workflows/verify.yml
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/submission_similarities_controller.rb
  app/views/api/v1/submission_similarities/report_template.html.erb
  config/routes.rb
  doc/SSID_API_Documentation.md
  spec/api_requests/api_v1_submission_similarities_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#384 Add viewing suspected students' submissions from History page for admin
  app/views/submission_logs/index.html.erb
  app/views/submission_similarities/_pair_report.html.erb
  app/views/submission_similarities/_pair_report_student_pair.html.erb
  app/views/submission_similarities/_student_history.erb
Labels: enhancement

#392 Fix: Broken font in logo
  app/assets/images/SSID_Logo.svg
Labels: Type: Refactor
