Repository WING-NUS/SSID, pull requests merged in 2023-11, with the labels that each got.

#371 Fix issue #370 SSID POST endpoints unable to work with Postman
  app/controllers/api/v1/assignments_controller.rb
Labels: bug

#374 Feature sort max and avg similarity first
  app/controllers/submission_similarities_controller.rb
  app/views/submission_similarities/index.html.erb
Labels: Type: Feature

#383 Feature: Implement new Landing Page
  app/assets/images/SSID_Logo.svg
  app/assets/images/add_circle_outline_blue_24dp.svg
  app/assets/images/avatar-icon.svg
  app/assets/images/chart-icon.svg
  app/assets/images/check_icon.svg
  app/assets/images/gradient-divider.png
  app/assets/images/integration-icon.svg
  app/assets/images/lightning-icon.svg
  app/assets/images/person_add_blue_24dp.svg
  app/assets/images/plus-circle.svg
  app/assets/images/ssid_cover_screenshot.png
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/scaffolds.css.scss
  app/assets/stylesheets/site.css.scss
  app/assets/stylesheets/submission_clusters.css.scss.erb
  app/views/layouts/application.html.erb
  app/views/layouts/cover.html.erb
Labels: Type: Feature

#385 Fix: Improve display of menu button
  app/assets/stylesheets/site.css.scss
  app/views/layouts/application.html.erb
Labels: Type: Bug
