Repository WING-NUS/SSID, pull requests merged in 2024-01, with the labels that each got.

#395 Edited User Guide based on latest version of system
  app/assets/images/add-course-info.jpeg
  app/assets/images/add-users.jpeg
  app/assets/images/confirm-plagiarism-prompt.jpeg
  app/assets/images/create-assignment.jpeg
  app/assets/images/create-groupings.jpeg
  app/assets/images/mark-as-suspicious-prompt.jpeg
  app/assets/images/pairwise-submission-highlight.jpeg
  app/assets/images/print-report-page.jpeg
  app/assets/images/print-report-prompt.jpeg
  app/assets/images/remove-plagiarism.jpeg
  app/assets/images/remove-user.jpeg
  app/assets/images/student-history-page.jpeg
  app/assets/images/update-course-user.jpeg
  app/assets/images/user-removal-confirmation.jpeg
  app/assets/images/view-course-users.jpeg
  app/assets/images/view-submissions-prompt.jpeg
  app/assets/images/view-visuals.jpeg
  app/views/layouts/guide.html.erb
Labels: Type: Documentation

#249 Add showing product update message
  README.md
  app/controllers/announcements_controller.rb
  app/controllers/application_controller.rb
  app/views/announcements/index.html.erb
  config/initializers/product_update.rb
  config/product_update/product_update.yml
  doc/set_product_update_message.md
  lib/tasks/set_product_update_message.rake
  lib/tasks/set_product_update_visibility.rake
Labels: enhancement

#186 Add maintenance mailer
  app/mailers/maintenance_mailer.rb
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.text.erb
  app/views/maintenance_mailer/maintenance_mailer.html.erb
  doc/send_maintenance_email_guide.md
  lib/tasks/send_maintenance_mail.rake
  test/mailers/maintenance_mailer_test.rb
  test/mailers/previews/maintenance_mailer_preview.rb
Labels: Type: Feature

#400 Fix skeleton code handling + wrong comparison in PR #389
  lib/java/PlagiarismDetection/src/pd/SimComparer.java
  lib/java/jar/PlagiarismDetection.jar
Labels: bug

#398 Fix crash when page size form is empty
  app/views/submission_similarities/index.html.erb
Labels: bug

#393 Fix null pointer exception of assignment processing status
  lib/submissions_handler.rb
Labels: bug

#304 Feature/obfuscation
  app/assets/javascripts/submission_obfuscation.js
  app/views/layouts/pdf_report.html.erb
  app/views/submission_similarities/_pair_report_student_pair.html.erb
  app/views/submission_similarities/_side_by_side_view.html.erb
  app/views/submission_similarities/index.html.erb
Labels: Type: Feature
